### ISSUE TITLE
mfem 4.2 does not build with Spectrum MPI 10.3.1.2 on Summit with xsdk cuda variant

### ISSUE THREAD

**Issue by luszczek** [xsdk-project/xsdk-issues#134]
I get compiler issues with MPICXX. See the Spack output below.

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5517990/spack-build-out.txt)

**Comment by balos1** [comment]
Mfem built fine on LLNL Lassen (POWER9) when building xsdk+cuda with spectrum 10.3.0.01.

**Comment by v-dobrev** [comment]
@luszczek, the `spack-build-out.txt` you posted does not use the correct mfem version. It has `MFEM_GIT_STRING = heads/mfem-4.2-dev-0-g97ad6956643fb84ae07c8c4b580f0bc00334de26` which is the branch `mfem-4.2-dev` instead of the v4.2 release itself. You probably just need to pull the latest `xsdk-0.6.0` branch where this is updated.

**Comment by luszczek** [comment]
I get the same message for version 4.2 for both OpenMPI and Spectrum MPI. Here are the output files for both.

[openmpi-spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5520828/openmpi-spack-build-out.txt)
[spectrummpi-spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5520829/spectrummpi-spack-build-out.txt)

**Comment by v-dobrev** [comment]
The error I see is:
```console
linalg/../fem/gslib.hpp:12:2: error: invalid preprocessing directive #ifndefMFEM_GSLIB
 #ifndefMFEM_GSLIB
  ^~~~~~~~~~~~~~~~
```
and the actual line is (https://github.com/mfem/mfem/blob/v4.2/fem/gslib.hpp#L12):
```c++
#ifndef MFEM_GSLIB
```
Could this be a bad patch in Spack? This is one of the files that had BOM in MFEM v4.1.

**Comment by luszczek** [comment]
You are correct, the patch didn't work. I had to change the patching for Unicode BOM in MFEM 4.1 with this (so it works for Python 2 and 3):
```python
import codecs
# Remove the byte order mark since it messes with some compilers
for f in ('fem/gslib.hpp', 'fem/gslib.cpp', 'linalg/hiop.hpp'):
  filter_file('0xef0xbb0xbf', '', f)  # save a copy of original
  d = open(f).read().replace(str(codecs.BOM_UTF8), '')
  open(f, 'w').write(d)
```

This resolves the issue so I'm closing it. Thank you for bearing with me.
