### ISSUE TITLE
openblas fails to build on Polaris with gcc@11.2.0

### ISSUE THREAD

**Issue by shuds13** [xsdk-project/xsdk-issues#196]
Setup:

module load PrgEnv-gnu

Spec:

xsdk@0.8.0 +cuda cuda_arch=80

Fails with

```bash
 /usr/bin/ld: ../libopenblas_zenp-r0.3.21.so: undefined reference to `_gfortran_concat_string'
```
I have tried adding `fflags=-glfortran` to spec and specifying 'extra_rpaths' to libgfortran.so in the spack.yaml. No difference.

[build.log](https://github.com/xsdk-project/xsdk-issues/files/9841968/build.log)
[spack.yaml.txt](https://github.com/xsdk-project/xsdk-issues/files/9841999/spack.yaml.txt)

More context (also see full log attached):

```bash

  [+] /tmp/shudson/xsdk/spack-xsdk/opt/spack/cray-sles15-zen3/gcc-11.2.0/bison-3.8.2-atkvngwrvghahhsctco33lpxtcgg4ype
==> Installing openblas-0.3.21-qb
[built_packages.txt](https://github.com/xsdk-project/xsdk-issues/files/9841980/built_packages.txt)
[spack.yaml.txt](https://github.com/xsdk-project/xsdk-issues/files/9841981/spack.yaml.txt)
oqf44zy7czhnxwjfehalnd4kbbpg6w
==> No binary for openblas-0.3.21-qboqf44zy7czhnxwjfehalnd4kbbpg6w found: installing from source
==> Fetching https://github.com/xianyi/OpenBLAS/archive/v0.3.21.tar.gz
==> No patches needed for openblas
==> openblas: Executing phase: 'edit'
==> openblas: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16' 'CC=/tmp/shudson/xsdk/spack-xsdk/lib/spack/env/gcc/gcc' 'FC=/tmp/shudson/xsdk/spack-xsdk/lib/spack/env/gcc/gfortran' 'MAKE_NB_JOBS=0' 'ARCH=x86_64' 'TARGET=ZEN' 'USE_LOCKING=1' 'USE_OPENMP=1' 'USE_THREAD=1' 'RANLIB=ranlib' 'libs' 'netlib' 'shared'

4 errors found in build log:
     7162    make[1]: Entering directory '/tmp/shudson/spack-stage/spack-stage-openblas-0.3.21-qboqf44zy7czhnxwjfehalnd4kbbpg6w/spack-src/expo
             rts'
     7163    ./gensymbol linktest  x86_64 _ 0 0 0 0 0 0 "" "" 1 0 1 1 1 1 > linktest.c
     7164    /tmp/shudson/xsdk/spack-xsdk/lib/spack/env/gcc/gcc -O2 -DSMALL_MATRIX_OPT -DMAX_STACK_ALLOC=2048 -DUSE_LOCKING -fopenmp -Wall -m6
             4 -DF_INTERFACE_INTEL -fPIC -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=256 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -
             DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.21\" -msse3 -msse4.1 -mavx -mavx2 -mavx2 -UASMNAME -UASMFNA
             ME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFF
             INITY -I..  -shared -o ../libopenblas_zenp-r0.3.21.so \
     7165    -Wl,--whole-archive ../libopenblas_zenp-r0.3.21.a -Wl,--no-whole-archive \
     7166    -Wl,-soname,libopenblas.so.0 -lm -lpthread -lm -lpthread
     7167    /tmp/shudson/xsdk/spack-xsdk/lib/spack/env/gcc/gcc -O2 -DSMALL_MATRIX_OPT -DMAX_STACK_ALLOC=2048 -DUSE_LOCKING -fopenmp -Wall -m6
             4 -DF_INTERFACE_INTEL -fPIC -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=256 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -
             DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.21\" -msse3 -msse4.1 -mavx -mavx2 -mavx2 -UASMNAME -UASMFNA
             ME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFF
             INITY -I..  -w -o linktest linktest.c ../libopenblas_zenp-r0.3.21.so  && echo OK.
  >> 7168    /usr/bin/ld: ../libopenblas_zenp-r0.3.21.so: undefined reference to `_gfortran_concat_string'
  >> 7169    collect2: error: ld returned 1 exit status
  >> 7170    make[1]: *** [Makefile:196: ../libopenblas_zenp-r0.3.21.so] Error 1
     7171    make[1]: Leaving directory '/tmp/shudson/spack-stage/spack-stage-openblas-0.3.21-qboqf44zy7czhnxwjfehalnd4kbbpg6w/spack-src/expor
             ts'
  >> 7172    make: *** [Makefile:125: shared] Error 2
```

**Comment by pghysels** [comment]
Perhaps you can try this commit: https://github.com/spack/spack/pull/33444
Or report it to spack directly.
I don't have this problem on Perlmutter with PrgEnv-gnu/8.3.3, gfortran 11.2.0.

**Comment by shuds13** [comment]
> Perhaps you can try this commit: [spack/spack#33444](https://github.com/spack/spack/pull/33444) Or report it to spack directly. I don't have this problem on Perlmutter with PrgEnv-gnu/8.3.3, gfortran 11.2.0.

Yes, openblas builds with this patch.

**Comment by balos1** [comment]
Closing as this seems to have been resolved.
