### ISSUE TITLE
hypre-2.26.0 build error in CI

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#179]
```
    272    /nfs/apps/spacks/2021-02-09/opt/spack/linux-centos7-x86_64/gcc-7.3.
            0/cuda-11.2.0-ikruu5mo6dtt3avvmwsejouqhxu4btdm/bin/nvcc -ccbin=/dat
            a/xsdkci/VS1mJQ1K/0/xsdk-project/spack-xsdk/opt/spack/linux-centos7
            -cascadelake/gcc-9.2.0/openmpi-4.1.4-3vy7mag5bckshhdx6egpb5zkt6shzz
            4q/bin/mpic++ -gencode arch=compute_70,code=sm_70  -O2 -lineinfo -e
            xpt-extended-lambda -std=c++11 --x cu -Xcompiler "-O2  -fPIC"  -DHA
            VE_CONFIG_H -I.. -I. -I./.. -I./../utilities  -I/nfs/apps/spacks/20
            21-02-09/opt/spack/linux-centos7-x86_64/gcc-7.3.0/cuda-11.2.0-ikruu
            5mo6dtt3avvmwsejouqhxu4btdm/include       -I/data/xsdkci/VS1mJQ1K/0
            /xsdk-project/spack-xsdk/opt/spack/linux-centos7-cascadelake/gcc-9.
            2.0/openmpi-4.1.4-3vy7mag5bckshhdx6egpb5zkt6shzz4q/include -c csr_m
            atvec_device.c -o csr_matvec_device.obj
  >> 273    csr_matvec_device.c(239): error: identifier "CUSPARSE_SPMV_CSR_ALG2
            " is undefined
     274    
  >> 275    csr_matvec_device.c(252): error: identifier "CUSPARSE_SPMM_CSR_ALG3
            " is undefined
     276    
  >> 277    csr_matvec_device.c(270): error: identifier "CUSPARSE_SPMM_CSR_ALG3
            " is undefined
     278    
  >> 279    csr_matvec_device.c(270): error: identifier "cusparseSpMM_preproces
            s" is undefined
     280    
  >> 281    csr_matvec_device.c(286): error: identifier "CUSPARSE_SPMV_CSR_ALG2
            " is undefined
     282    
  >> 283    csr_matvec_device.c(299): error: identifier "CUSPARSE_SPMM_CSR_ALG3
            " is undefined
```
ref: https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/3102857094

$ nice ./bin/spack install -j24 xsdk@0.8.0+cuda cuda_arch=70 ^cuda@11.2.0 ^openmpi

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/9676264/spack-build-out.txt)

**Comment by victorapm** [comment]
@ulrikeyang I can take a look at this

**Comment by balay** [comment]
Ah - I suspect this is due to `cuda@11.2.0`.

I have a different build with `cuda@11.6.0` and that went through fine.

```
balay@xsdk:/data/balay/spack>./bin/spack find hypre cuda
==> 3 installed packages
-- linux-centos7-cascadelake / gcc@9.2.0 ------------------------
cuda@11.6.0  hypre@2.26.0  hypre@2.26.0
```

So if there is a real dependency on  newer cuda versions - perhaps there needs to be checks in configure - and spack...

**Comment by victorapm** [comment]
Thanks @balay! I also have other working builds with `cuda > 11.2.0`. We do have an internal check in hypre for enabling those macros, but it seems that the minimum cuda version we are using is wrong, see

https://github.com/hypre-space/hypre/blob/8dc524e8a17a549575f59a5147602ed89a6c59e3/src/seq_mv/csr_matvec_device.c#L20 

and

https://github.com/hypre-space/hypre/blob/8dc524e8a17a549575f59a5147602ed89a6c59e3/src/utilities/_hypre_utilities.hpp#L98

I'll update this.

**Comment by balay** [comment]
on my end - I'm switching my testing to use 11.6.0 [testing the newer cuda version makes sense for the newer xsdk release anyway]

**Comment by victorapm** [comment]
@balay, FYI, the fix has been merged into hypre's `master`

**Comment by balos1** [comment]
Passing here: https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/3175131930
