### ISSUE TITLE
hypre@3.0.0+superlu-dist build failure

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#279]
```
balay@pj02:~/spack.x$ ./bin/spack install hypre+superlu-dist
<snip>
==> Installing hypre-3.0.0-k6kfmyug2gwggqkhsxa33nlgr5pfbjxr [51/51]
==> Fetching https://github.com/hypre-space/hypre/archive/v3.0.0.tar.gz
    [100%]    8.06 MB @    5.2 MB/s
==> No patches needed for hypre
==> hypre: Executing phase: 'cmake'
==> Error: ProcessError: Command exited with status 1:
    '/home/balay/spack.x/opt/spack/linux-skylake/cmake-3.31.9-7rnr2abhyc3wt2gjy3qw2jiyfxu5of6c/bin/cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:STRING=/home/balay/spack.x/opt/spack/linux-skylake/hypre-3.0.0-k6kfmyug2gwggqkhsxa33nlgr5pfbjxr' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON' '-DCMAKE_INSTALL_RPATH:
STRING=/home/balay/spack.x/opt/spack/linux-skylake/hypre-3.0.0-k6kfmyug2gwggqkhsxa33nlgr5pfbjxr/lib;/home/balay/spack.x/opt/spack/linux-skylake/hypre-3.0.0-k6kfmyug2gwggqkhsxa33nlgr5pfbjxr/lib64' '-DCMAKE_PREFIX_PATH:STRING=/home/balay/spack.x/opt/spack/linux-skylake/cmake-3.31.9-7rnr2abhyc3wt2gjy3qw2jiyfxu5of6c;/hom
e/balay/spack.x/opt/spack/linux-skylake/compiler-wrapper-1.0-rjwvfvzu7uah765ljas7sc43kys7h25v;/home/balay/spack.x/opt/spack/linux-skylake/gmake-4.4.1-352pwtwmkntpplr3qvgehegzwy3k23c5;/home/balay/spack.x/opt/spack/linux-skylake/superlu-dist-9.1.0-b3avz6lq6ibtareorbfyftwydv5cbfwh;/home/balay/spack.x/opt/spack/linux-sky
lake/openblas-0.3.30-crmyczpdv2o3k33mfggggrtxainxmqac;/home/balay/spack.x/opt/spack/linux-skylake/parmetis-4.0.3-l73egmmcuheoaojyaqjqgrkh6pwf5v7t;/home/balay/spack.x/opt/spack/linux-skylake/metis-5.1.0-dpgufhlkhd7uentu3e246bita4pfe5fv;/home/balay/spack.x/opt/spack/linux-skylake/openmpi-5.0.9-wlsj7bizmwssttvo7dmvukzje
ktjpxew;/home/balay/spack.x/opt/spack/linux-skylake/numactl-2.0.18-7ek5cdu3aig77fwvv4tqgn6yvsra36iq;/home/balay/spack.x/opt/spack/linux-skylake/prrte-4.0.0-sg3y2m2rbeffjqyglfe3rdsvrpohkhvp;/home/balay/spack.x/opt/spack/linux-skylake/pmix-6.0.0-dscbltcjmcvnzhhztb6zscqnvlfdykzf;/home/balay/spack.x/opt/spack/linux-skyla
ke/hwloc-2.12.2-klizsxyqo2vo5btbgs7hgyf2ppf5vvr6;/home/balay/spack.x/opt/spack/linux-skylake/libevent-2.1.12-phld3hb4bq4w4ros6bzgt2s2yrknlhzx;/home/balay/spack.x/opt/spack/linux-skylake/libpciaccess-0.17-ugzta2dwrhzot5sqaxckhnm2aistpzcw;/home/balay/spack.x/opt/spack/linux-skylake/libxml2-2.13.5-mvqqzlfz4u4hpkdrozgq4d
3y3pzx4w2q;/home/balay/spack.x/opt/spack/linux-skylake/ncurses-6.5-20250705-uhm7lts7ealprf2rady747narrejlodq;/home/balay/spack.x/opt/spack/linux-skylake/openssl-3.6.0-evxvnhzd4bglcoklxjzyur77fkkp6tzf;/home/balay/spack.x/opt/spack/linux-skylake/libiconv-1.18-4ro6rmdgy7gql3nj4szvf2ag2wun2mhg;/home/balay/spack.x/opt/spa
ck/linux-skylake/xz-5.6.3-6cmhv3mmgcvtwz5vgcqzo7amn4df4huw;/home/balay/spack.x/opt/spack/linux-skylake/zlib-ng-2.2.4-tplghov7z4v3s4qatjdi4arglocpq6bd;/home/balay/spack.x/opt/spack/linux-skylake/gcc-runtime-14.3.1-j5dk52ea6xvceuhwyfwffslz2eptqzwp' '-DCMAKE_BUILD_TYPE:STRING=Release' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' 
'-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=OFF' '-DCMAKE_POLICY_DEFAULT_CMP0090:STRING=NEW' '-DCMAKE_FIND_USE_PACKAGE_REGISTRY:BOOL=OFF' '-DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON' '-DBUILD_SHARED_LIBS:BOOL=OFF' '-DCMAKE_CXX_STANDARD:STRING=17' '-DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON' '-DHYPRE_ENABLE_MPI:BOOL=ON' '-
DHYPRE_ENABLE_OPENMP:BOOL=OFF' '-DHYPRE_ENABLE_FORTRAN:BOOL=OFF' '-DHYPRE_ENABLE_COMPLEX:BOOL=OFF' '-DHYPRE_ENABLE_BIGINT:BOOL=OFF' '-DHYPRE_ENABLE_MIXEDINT:BOOL=OFF' '-DHYPRE_ENABLE_SINGLE:BOOL=OFF' '-DHYPRE_ENABLE_LONG_DOUBLE:BOOL=OFF' '-DHYPRE_ENABLE_MIXED_PRECISION:BOOL=OFF' '-DHYPRE_ENABLE_HYPRE_BLAS:BOOL=ON' '-
DHYPRE_ENABLE_HYPRE_LAPACK:BOOL=ON' '-DHYPRE_ENABLE_CUDA:BOOL=OFF' '-DHYPRE_ENABLE_HIP:BOOL=OFF' '-DHYPRE_ENABLE_SYCL:BOOL=OFF' '-DHYPRE_ENABLE_GPU_AWARE_MPI:BOOL=OFF' '-DHYPRE_ENABLE_GPU_PROFILING:BOOL=OFF' '-DHYPRE_ENABLE_UNIFIED_MEMORY:BOOL=OFF' '-DHYPRE_ENABLE_UMPIRE:BOOL=OFF' '-DHYPRE_ENABLE_CALIPER:BOOL=OFF' '-
DHYPRE_ENABLE_DSUPERLU:BOOL=ON' '-DHYPRE_ENABLE_MAGMA:BOOL=OFF' '/home/balay/spack.x/spack-stage/spack-stage-hypre-3.0.0-k6kfmyug2gwggqkhsxa33nlgr5pfbjxr/spack-src/src'

1 error found in build log:
     19    -- MPI execution command: /home/balay/spack.x/opt/spack/linux-skylake/openmpi-5.0.9-wlsj7bizmwssttvo7dmvukzjektjpxew/bin/mpiexec
     20    -- Performing Test HYPRE_HAVE_MPI_COMM_F2C
     21    -- Performing Test HYPRE_HAVE_MPI_COMM_F2C - Success
     22    -- Link-Time Optimization (LTO) disabled
     23    -- GPU support not enabled
     24    -- Could NOT find dsuperlu (missing: dsuperlu_DIR)
  >> 25    CMake Error at config/cmake/HYPRE_CMakeUtilities.cmake:314 (message):
     26      DSUPERLU target not found.  Please check your DSUPERLU installation
     27    Call Stack (most recent call first):
     28      CMakeLists.txt:439 (setup_tpl)
     29    
     30    
     31    -- Configuring incomplete, errors occurred!

See build log for details:
  /home/balay/spack.x/spack-stage/spack-stage-hypre-3.0.0-k6kfmyug2gwggqkhsxa33nlgr5pfbjxr/spack-build-out.txt
```
This works though..
```
balay@pj02:~/spack.x$ ./bin/spack install hypre@2.33.0+superlu-dist
<snip>
==> No binary for hypre-2.33.0-kldws2hjjtfn557gk5467n4y6w5j6tro found: installing from source
==> Installing hypre-2.33.0-kldws2hjjtfn557gk5467n4y6w5j6tro [32/32]
==> Fetching https://mirror.spack.io/_source-cache/archive/0f/0f9103c34bce7a5dcbdb79a502720fc8aab4db9fd0146e0791cde7ec878f27da.tar.gz
    [100%]    7.51 MB @  104.7 MB/s
==> No patches needed for hypre
==> hypre: Executing phase: 'autoreconf'
==> hypre: Executing phase: 'configure'
==> hypre: Executing phase: 'build'
==> hypre: Executing phase: 'install'
==> hypre: Successfully installed hypre-2.33.0-kldws2hjjtfn557gk5467n4y6w5j6tro
  Stage: 0.46s.  Autoreconf: 0.00s.  Configure: 1.99s.  Build: 28.20s.  Install: 0.11s.  Post-install: 0.04s.  Total: 30.88s
[+] /home/balay/spack.x/opt/spack/linux-skylake/hypre-2.33.0-kldws2hjjtfn557gk5467n4y6w5j6tro
```

cc: @victorapm

**Comment by xiaoyeli** [comment]
It looks like DSUPERLU is not defined.

Sherry

**Comment by victorapm** [comment]
Hi all, I can work on fixing this

**Comment by balay** [comment]
@victorapm, with the above fix:

```
balay@pj02:~/spack.x$ ./bin/spack install petsc@3.24.1+hypre ^hypre@3.0.0+superlu-dist+shared
```
gives a petsc build failure with:

```
/usr/bin/ld: /home/balay/spack.x/opt/spack/linux-skylake/hypre-3.0.0-6n3t2ibktphqjcvrhook4y4lcodlhfsp/lib64/libHYPRE.so: undefined reference to `hypre_SLUDistDestroy'
/usr/bin/ld: /home/balay/spack.x/opt/spack/linux-skylake/hypre-3.0.0-6n3t2ibktphqjcvrhook4y4lcodlhfsp/lib64/libHYPRE.so: undefined reference to `hypre_SLUDistSetup'
/usr/bin/ld: /home/balay/spack.x/opt/spack/linux-skylake/hypre-3.0.0-6n3t2ibktphqjcvrhook4y4lcodlhfsp/lib64/libHYPRE.so: undefined reference to `hypre_SLUDistSolve'
```
```
balay@pj02:~/spack.x$ nm -Ao /home/balay/spack.x/opt/spack/linux-skylake/hypre-3.0.0-6n3t2ibktphqjcvrhook4y4lcodlhfsp/lib64/libHYPRE.so |grep hypre_SLUDistDestroy
/home/balay/spack.x/opt/spack/linux-skylake/hypre-3.0.0-6n3t2ibktphqjcvrhook4y4lcodlhfsp/lib64/libHYPRE.so:                 U hypre_SLUDistDestroy
```
Also perhaps its good to have  '+shared' as default?

**Comment by victorapm** [comment]
Hi Satish, we have a fix for the linking issues in `master` already. I'm back-porting a patch so the build with `hypre@3.0.0` works as well here: https://github.com/spack/spack-packages/pull/2501/commits/386a821979514406ee5169d8be8affc8fd17e219.

Regarding defaults, we have a new `pic` variant now. Would `pic` as default be enough in your opinion? Thanks!

**Comment by balay** [comment]
Thanks!  my builds are successful with this fix!

BTW: I'm not yet sure if I can use hypre-3 in xsdk - due to mfem dependencies [as there is no mfem release with hypre-3.0 fixes]. cc: @v-dobrev

**Comment by balay** [comment]
> Would pic as default be enough in your opinion

I think defaulting to libhypre.so instead of libhypre.a is more useful.

pic helps only if - say libpetsc.so is built with a libhypre.a dependency - but here all hypre symbols get into libpetsc.so - so not ideal.. (esp if one creates libpetsc.so libmfem.so etc this way..)

I think most pkg builds default to shared

**Comment by victorapm** [comment]
Thanks for the feedback, Satish, that's a good point. I changed the defaults to `+shared ~pic` on the spack PR. I also updated the patch for the build issue with mixed precision discussed here: https://gitlab.com/petsc/petsc/-/issues/1828

**Comment by balay** [comment]
BTW: generally '-fPIC' is a requirement for '+shared' - so I'm not sure if '+shared ~pic' will work (on all builds)

**Comment by victorapm** [comment]
Good point... Experimenting with`cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_POSITION_INDEPENDENT_CODE=OFF`, I still see the `fPIC` flag being added, so I'm not sure if `+shared ~pic` is an issue, unless I'm missing something

**Comment by balay** [comment]
generally exposing 'pic' on configure interface doesn't make sense. However we have it for petsc configure for the following reason:
- configure test for detecting -fPIC flag can be broken (for whatever reason) - so in this case user can workaround with something like:
```
./configure  --with-shared-libraries=1 CFLAGS=-fPIC --with-pic=0
```

From the above description - looks like cmake is ignoring CMAKE_POSITION_INDEPENDENT option - when BUILD_SHARED_LIBS=ON is set.. (I'm not sure how one would expose such 'ignore' in spack interface..)

**Comment by victorapm** [comment]
Interesting... We have users that need to build hypre in static mode while they application is built in shared mode, so they need `fPIC` in hypre. That can be accomplished by passing `cflags=-fPIC`, but we added a `pic` variant to make it easier...

**Comment by v-dobrev** [comment]
> BTW: I'm not yet sure if I can use hypre-3 in xsdk - due to mfem dependencies [as there is no mfem release with hypre-3.0 fixes]. cc: [@v-dobrev](https://github.com/v-dobrev)

The upcoming mfem v4.9 will support hypre v3.0.0. In Spack, `mfem@develop` should already support that too.

**Comment by balay** [comment]
Thanks @v-dobrev ! I'm currently using mfem/master branch [as @4.9.0]
